### ISSUE TITLE
The /statements/{statementid} JSON values not accurate and complete

### ISSUE THREAD

**Issue by RichardBruskiewich** [NCATS-Tangerine/ndex-beacon#22]
This endpoint needs more iteration:

* *is_defined_by (string, optional):* A CURIE/URI for the translator group that wrapped this knowledge source ('beacon') that publishes the statement made in an edge.  -**should be http://starinformatics.com (since the STAR team built the beacon)**

* *provided_by (string, optional):* A CURIE prefix, e.g. Pharos, MGI, Monarch. The group that curated/asserted the statement made in an edge.  - **should actually be the owner of the network which contained this edge. Of course, NDEX is the archive source, but the graph data came from somebody else.**

* *evidence:* - I'm wondering if the literature citation supporting the source data set is somehow available as a comment on the network which gave the edge (statement)?

**Comment by isuen** [comment]
provided_by: use NDEX:network-id for now
