### ISSUE TITLE
Fix pagination

### ISSUE THREAD

**Issue by lhannest** [NCATS-Tangerine/ndex-beacon#3]
https://ndex-kb.ncats.io/statements?c=087f49c6-0d90-11e6-b550-06603eb7f303%3A1058&pageNumber=1&pageSize=1&semgroups=

https://ndex-kb.ncats.io/statements?c=087f49c6-0d90-11e6-b550-06603eb7f303%3A1058&pageNumber=2&pageSize=1&semgroups=

Each page returns the same data. It looks like there are only two items to return on the first page, so the second page should be empty

**Comment by RichardBruskiewich** [comment]
Although the V2.1 nDex API has page number and size arguments, these either seem to be ignored completely or perhaps, the code is not properly conveying the parameters to the index API endpoint. Not yet sure which is which. Some kind of beacon in memory caching strategy could perhaps be used to buffer the ndex results as pages(?)

**Comment by RichardBruskiewich** [comment]
I think that this is fixed - the beacon caches all data from a given query and resends page views on request -  although the above concept ids (which are esoteric ndex ones) don't actually return any data! 

The correctness of pagination was reviewed by eye but the beacon-validator seems to fail this test for concepts. This needs to be checked so again, keeping this issue open for now.
