### ISSUE TITLE
nDex beacon doesn't return proper evidence

### ISSUE THREAD

**Issue by RichardBruskiewich** [NCATS-Tangerine/ndex-beacon#6]
nDex beacon fails the validator workflow test since it fails to properly return evidence associated with "statements". This partly seems to be due to sloppy management of statement ids but also perhaps the challenge of figuring out what ndex network annotation constitutes appropriate evidence(?)

**Comment by cmungall** [comment]
Perhaps just use the graph id as evidence for now?

**Comment by RichardBruskiewich** [comment]
nDex fixed to return at least an associated graph network as "evidence" and TKBio also modified to render that nDex web page with the graph, when prompted
